# -*- coding: utf-8 -*-
"""filtering aap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RO3bgeLDjdCpuolfblq5OA-lEgiuKkUs
"""

#!/usr/bin/env python3
"""
Step 1: Filter tweets mentioning Apple stocks ($AAPL)
"""

import pandas as pd
import re

def filter_apple_tweets(input_csv, output_csv):
    """
    Filter tweets that mention Apple stocks (AAPL or apple) and save to a new CSV.
    """
    # Read the dataset
    df = pd.read_csv(input_csv)

    # Convert post_date to datetime (assuming Unix timestamp)
    df['post_date'] = pd.to_datetime(df['post_date'], unit='s')

    # Define regex pattern for Apple stock mentions
    pattern = re.compile(r'(\$aapl|aapl|apple)', re.IGNORECASE)

    # Filter tweets that contain Apple stock mentions
    apple_tweets = df[df['body'].apply(lambda x: bool(pattern.search(x)))]

    # Save to new CSV
    apple_tweets.to_csv(output_csv, index=False)

    print(f"Filtered {len(apple_tweets)} Apple-related tweets out of {len(df)} total tweets")
    return apple_tweets

if __name__ == "__main__":
    # Change these paths to match your files
    input_csv = "Tweet.csv"
    output_csv = "apple_tweets.csv"

    # Run the filter
    filter_apple_tweets(input_csv, output_csv)
    print(f"Filtered tweets saved to {output_csv}")
